mock-server/api/v1/microlc/configuration/get.js
packages/core/src/models/configuration/index.ts
packages/core/src/models/configuration/theming/Logo.ts
packages/core/src/models/configuration/theming/Theming.ts
packages/core/src/models/model.ts
packages/fe-container/src/components/side-menu/SideMenu.test.tsx
packages/fe-container/src/components/top-bar/TopBar.tsx
packages/fe-container/src/hooks/useConfiguration.ts
packages/fe-container/src/plugins/PluginsLoaderFacade.test.ts
packages/fe-container/src/plugins/PluginsLoaderFacade.ts

- Improved configuration strategy
- Logo alt is now configurable

[BRD-139] - Strategy improvements

---

mock-server/api/v1/microlc/authentication/get.js
packages/core/src/models/authentication/Authentication.ts
packages/core/src/models/authentication/index.ts
packages/core/src/models/model.ts
packages/fe-container/src/__tests__/App.test.tsx
packages/fe-container/src/components/side-menu/SideMenu.test.tsx
packages/fe-container/src/components/top-bar/TopBar.tsx
packages/fe-container/src/components/user-menu/UserMenu.test.tsx
packages/fe-container/src/components/user-menu/UserMenu.tsx
packages/fe-container/src/constants.ts
packages/fe-container/src/hooks/useAppData/useAppData.test.ts
packages/fe-container/src/services/microlc/__tests__/authentication.service.test.ts
packages/fe-container/src/services/microlc/__tests__/microlc.service.test.ts
packages/fe-container/src/services/microlc/__tests__/user.service.test.ts
packages/fe-container/src/services/microlc/authentication.service.ts
packages/fe-container/src/services/microlc/microlc.service.ts
packages/fe-container/src/services/microlc/user.service.ts
packages/fe-container/src/utils/plugins/PluginsLoaderFacade.ts
packages/fe-container/src/utils/plugins/strategies/HrefStrategy.ts
packages/fe-container/src/utils/plugins/strategies/NoOpStrategy.ts
packages/fe-container/src/utils/plugins/strategies/RouteStrategy.ts
packages/fe-container/src/utils/plugins/strategies/__tests__/HrefStrategy.test.ts
packages/fe-container/src/utils/plugins/strategies/__tests__/NoOpStrategy.test.ts
packages/fe-container/src/utils/plugins/strategies/__tests__/RouteStrategy.test.ts

- User information retrieve from configurable endpoints
- Strategies exctrations
- Better unit testing

[BRD-47] - User info

---

packages/fe-container/src/components/layout-content/LayoutContent.less
packages/fe-container/src/components/layout-content/LayoutContent.tsx
packages/fe-container/src/utils/plugins/PluginsLoaderFacade.ts

Removed layout content management with router, to increment performance

Layout content fixes

---

packages/fe-container/package.json
packages/fe-container/src/components/microlc-error-boundary/MicrolcErrorBoundary.test.tsx
packages/fe-container/src/components/microlc-error-boundary/MicrolcErrorBoundary.tsx
packages/fe-container/src/containers/launcher/Launcher.tsx
packages/fe-container/src/strings/locales/en.json
packages/fe-container/src/strings/locales/it.json
yarn.lock

Error boundary with temporary error component

[BRD-55] - Error boundary

---

packages/fe-container/package.json
packages/fe-container/src/styles/_colors.less
packages/fe-container/src/utils/plugins/PluginsLoaderFacade.ts
packages/fe-container/src/utils/theme/ThemeManager.test.ts
packages/fe-container/src/utils/theme/ThemeManager.ts
yarn.lock

Primary color calculation using tint weight = 89

[BRD-159] - Primary color

---

packages/be-config/package.json
packages/be-config/src/__tests__/configurationMocks/validMicrolcConfigNoPlugins.json
packages/be-config/src/apis/__tests__/configurationApi.test.ts
packages/be-config/src/apis/configurationApi.ts
packages/be-config/src/constants.ts
packages/be-config/src/utils/__tests__/pluginsFilter.test.ts
packages/be-config/src/utils/pluginsFilter.ts
packages/core/src/models/configuration/plugin/Plugin.ts
packages/fe-container/nginx/conf.d/website.conf

[BRD-157] - Plugins filter

---

mock-server/api/v1/microlc/authentication/get.js
packages/be-config/src/__tests__/configurationMocks/validAuthenticationConfig.json
packages/be-config/src/apis/__tests__/authenticationApi.test.ts
packages/be-config/tsconfig.json
packages/core/src/models/authentication/Authentication.ts
packages/fe-container/src/components/user-menu/UserMenu.test.tsx
packages/fe-container/src/constants.ts
packages/fe-container/src/services/microlc/__tests__/user.service.test.ts
packages/fe-container/src/services/microlc/microlc.service.ts
packages/fe-container/src/services/microlc/user.service.ts
yarn.lock

Configurable logout url

---

.gitignore
.vscode/settings.json
packages/fe-container/src/components/help-icon/HelpIcon.less
packages/fe-container/src/components/help-icon/HelpIcon.test.tsx
packages/fe-container/src/components/help-icon/HelpIcon.tsx
packages/fe-container/src/components/top-bar/TopBar.less
packages/fe-container/src/components/top-bar/TopBar.test.tsx
packages/fe-container/src/components/top-bar/TopBar.tsx
packages/fe-container/src/constants.ts

implemented the help button with redirection to the doc page and burger icon is not rendered when plugin list is empty

[BRD-166-167] - Help Button and Hide Burger Icon 

---

packages/fe-container/src/components/help-icon/HelpIcon.less
packages/fe-container/src/components/layout-content/LayoutContent.less
packages/fe-container/src/components/layout-content/LayoutContent.tsx
packages/fe-container/src/containers/error-page/ErrorPageContainer.less
packages/fe-container/src/containers/error-page/ErrorPageContainer.tsx
packages/fe-container/src/containers/launcher/Launcher.less
packages/fe-container/src/containers/launcher/Launcher.tsx
packages/fe-container/src/utils/plugins/PluginsLoaderFacade.ts
packages/fe-container/src/utils/plugins/strategies/RouteStrategy.ts
packages/fe-container/src/utils/plugins/strategies/__tests__/RouteStrategy.test.ts

Layout content refresh on click item

[BRD-168] - Layout content

---

mock-server/api/v1/microlc/configuration/get.js
mock-server/configuration.js
packages/be-config/src/__tests__/configurationMocks/validMicrolcConfig.json
packages/be-config/src/__tests__/configurationMocks/validMicrolcConfigNoPlugins.json
packages/core/src/models/configuration/Configuration.ts
packages/core/src/models/configuration/helpMenu/HelpMenu.ts
packages/core/src/models/configuration/theming/Logo.ts
packages/fe-container/src/App.less
packages/fe-container/src/components/dark-mode-switch/DarkModeSwitch.test.tsx
packages/fe-container/src/components/dark-mode-switch/DarkModeSwitch.tsx
packages/fe-container/src/components/help-icon/HelpIcon.test.tsx
packages/fe-container/src/components/help-icon/HelpIcon.tsx
packages/fe-container/src/components/top-bar/TopBar.test.tsx
packages/fe-container/src/components/top-bar/TopBar.tsx

1- fixed white bar
2- help button customizable
3- logo based on theme

[BRD-173] - Fix demo

---

README.md
e2e/__tests__/topbar.spec.ts
e2e/config/microlcConfig.json
mock-server/configuration.js
packages/be-config/src/__tests__/configurationMocks/validMicrolcConfig.json
packages/be-config/src/__tests__/configurationMocks/validMicrolcConfigNoPlugins.json
packages/core/src/models/configuration/theming/Logo.ts
packages/fe-container/src/__tests__/App.test.tsx
packages/fe-container/src/components/layout-content/LayoutContent.test.tsx
packages/fe-container/src/components/top-bar/TopBar.less
packages/fe-container/src/components/top-bar/TopBar.test.tsx
packages/fe-container/src/components/top-bar/TopBar.tsx
packages/fe-container/src/hooks/useAppData/useAppData.test.ts
packages/fe-container/src/services/microlc/__tests__/microlc.service.test.ts
packages/fe-container/src/utils/theme/ThemeManager.test.ts

Clicking on logo now redirects to a custom page got from the configuration

[RXDP-11] - Custom Logo Redirection

---

mock-server/configuration.js
packages/fe-container/src/components/dark-mode-switch/DarkModeSwitch.less
packages/fe-container/src/components/footer-bar/FooterBar.less
packages/fe-container/src/components/layout-content/LayoutContent.less
packages/fe-container/src/components/top-bar-menu/TopBarMenu.less
packages/fe-container/src/components/top-bar/TopBar.less
packages/fe-container/src/containers/error-page/ErrorPageContainer.less
packages/fe-container/src/styles/_colors.less
packages/fe-container/src/styles/_variables.less

some adjustments for the new dark theme design

[RXDP-30-31] - Dark Theme

---

packages/fe-container/src/components/layout-content/LayoutContent.tsx
packages/fe-container/src/constants.ts
packages/fe-container/src/utils/plugins/PluginsLoaderFacade.test.ts
packages/fe-container/src/utils/plugins/PluginsLoaderFacade.ts
packages/fe-container/src/utils/plugins/strategies/RouteStrategy.ts
packages/fe-container/src/utils/plugins/strategies/__tests__/RouteStrategy.test.ts

Inserted loading animation when navigating between plugins, instead of 404 page.

[RXDP-37] - Loading animation on navigation

---

e2e/__tests__/analytics.spec.ts
e2e/__tests__/qiankun.spec.ts
e2e/__tests__/usermenu.spec.ts
e2e/config.ts
package.json
packages/fe-container/package.json
packages/fe-container/src/components/burger-icon/BurgerIcon.test.tsx
packages/fe-container/src/components/dark-mode-switch/DarkModeSwitch.test.tsx
packages/fe-container/src/components/dark-mode-switch/DarkModeSwitch.tsx
packages/fe-container/src/components/footer-bar/FootBar.test.tsx
packages/fe-container/src/components/footer-bar/FooterBar.tsx
packages/fe-container/src/components/microlc-error-boundary/MicrolcErrorBoundary.test.tsx
packages/fe-container/src/components/top-bar/TopBar.test.tsx
packages/fe-container/src/components/user-menu/UserMenu.test.tsx
packages/fe-container/src/constants.ts
packages/fe-container/src/utils/plugins/PluginsLoaderFacade.test.ts
packages/fe-container/src/utils/settings/analytics/AnalyticsSettingsManager.test.ts
packages/fe-container/src/utils/settings/analytics/AnalyticsSettingsManager.ts
packages/fe-container/src/utils/settings/dark-mode/DarkModeSettings.test.ts
packages/fe-container/src/utils/settings/dark-mode/DarkModeSettings.ts

Dark mode configuration now persist in local storag

[RXDP-33] - Dark mode persistent

---

packages/fe-container/src/hooks/useAppData/useAppData.ts

Speed up navigation to first plugin, in order to avoid the 404 page flash

[RXDP-53] - Speed up navigation to plugin first process

---

README.md

Just adding the introduction video on README.md.
Please check if works well also for you.

add YouTube introduction video on README.md

---

mock-server/api/v1/microlc/configuration/configuration.json
packages/fe-container/src/components/help-icon/HelpIcon.test.tsx

change of the old documentation url with: microlc.io/documentation/

updated helper link with new documentation link

---

packages/fe-container/Dockerfile
packages/fe-container/nginx/conf.d/website.conf
packages/fe-container/start-scripts/prerender.sh

Prerender seo

---

.vscode/launch.json
scripts/version.mjs

-> no more `micro-lc` job
-> became a side effect of the `orchestrator` job

rework of version cli

---

packages/orchestrator/CHANGELOG.md
packages/orchestrator/vite.config.ts
tests/config.spec.ts
tests/dev/index.html
tests/server.ts

Starting from version 2.9.1 there seems to be a problem with deduping qiankun if this is bundled in its own chunk.

development mode correctly imports qiankun

---

.github/dependabot.yml
packages/orchestrator/CHANGELOG.md
packages/orchestrator/package.json
packages/orchestrator/src/web-component/lib/router.ts
playground.mjs
yarn.lock

speedy sandbox excluded when mounting parcels
qiankun version bump

qiankun up to latest

---

.docker/Dockerfile
packages/orchestrator/CHANGELOG.md

NGINX to version 1.24.0

---

package.json
packages/iconic/CHANGELOG.md
packages/iconic/package.json
packages/iconic/scripts/list-icons.ts
yarn.lock

Added script to iconic package that creates a list of available icons in the final bundle.

Icons list script

---

.docker/Dockerfile
packages/orchestrator/CHANGELOG.md

fixes for `nginx:1.24.0-alpine` vulnerabilities
Vulnerability    Severity Package                                  Type     Fix version      URL
- CVE-2023-28319   High     curl-7.88.1-r1                           APKG     8.1.0-r0         https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28319
- CVE-2023-28320   Medium   curl-7.88.1-r1                           APKG     8.1.0-r0         https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28320
- CVE-2023-28321   High     curl-7.88.1-r1                           APKG     8.1.0-r0         https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28321
- CVE-2023-28322   Critical curl-7.88.1-r1                           APKG     8.1.0-r0         https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28322
- CVE-2023-1255    Medium …

security: Dockerfile security fixes

---

packages/iconic/CHANGELOG.md
packages/iconic/scripts/bundle-icons.ts

Added Ant Design icons to iconic bundle

Added ant icons to iconic bundle

---

.github/workflows/tag.yml

in `.github/workflows/tag.yml`: split lib publish steps in
- npm
- cdn.mia-platform.eu

split lib publish steps in -> npm -> cdn.mia-platform.eu

---

.docker/Dockerfile
packages/orchestrator/CHANGELOG.md

fixed vulnerabilities on:
- tiff
- libx11

security: fixing CVEs on `micro-lc` Dockerfile

---

.docker/Dockerfile
packages/orchestrator/CHANGELOG.md

Update Dockerfile to mitigate `CVE-2023-38039`

Update Dockerfile for security fixes

---

packages/composer/CHANGELOG.md
packages/composer/src/lib/lexer.ts
packages/composer/src/lib/test/lexer.test.ts

- lexer was throwing when reaching the end in normal mode which is not necessary
- refactor to lexer in order to remove a pre-minified version
- throw unit test removed and replaced with its non-throwing version
- added some tests

fix(composer): lexer throw removed

---

CHANGELOG.md
packages/orchestrator/CHANGELOG.md
packages/orchestrator/src/utils/lang.ts
packages/orchestrator/src/utils/test/lang.test.ts
packages/orchestrator/src/web-component/micro-lc.ts
tests/config.spec.ts
tests/pages/language.html

Added `fallback-language` property in micro-lc web component

Comp 147/fallback language

---

packages/composer/CHANGELOG.md
packages/composer/src/index.ts
packages/orchestrator/CHANGELOG.md
packages/orchestrator/src/web-component/lib/extensions.ts
packages/orchestrator/src/web-component/micro-lc.ts
tests/composer.test.ts

Made composer able to use fallback-language value inherited from micro-lc web component

Comp 275/compose fallback lang

---

packages/orchestrator/CHANGELOG.md
packages/orchestrator/package.json
yarn.lock

Fix typo in `@micro-lc/orchestrator` peer-deps package.json section

fix(deps-dev): fix typo in @micro-lc/orchestrator peer-dependecies section

---

packages/composer/CHANGELOG.md
packages/composer/src/lib/index.ts
packages/orchestrator/CHANGELOG.md

Sources of ResolvedConfig has been decorated with an additional field modules which contains data exported by dynamically imported modules

Added module data to resolved config
